import Head from "next/head"
import { useState } from "react"
import Header from "../components/Header"
import Intro from "../components/Intro"
import BigLogo from "../components/subComponents/BigLogo"
import DarkSide from "../components/subComponents/DarkSide"
import Socials from "../components/subComponents/Socials"

export default function Home() {
  const [click, setClick] = useState(false)

  const handleClick = () => setClick(!click)

  return (
    <div className="page">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header click={click} />
      <DarkSide click={click} />
      <BigLogo click={click} handleClick={handleClick} />
      <Socials click={click} />
      {click ? <Intro click={click} /> : null}
    </div>
  )
}
